version: "3.8"

services:

  shop-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-api
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shopdb
    networks:
      - monitoring-net

  db:
    image: postgres:14
    container_name: shop-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shopdb"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  postgres_data: