
version: "3"

services:

  local:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    restart: always
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: hw4_db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: hw4_postgres
    environment:
      POSTGRES_DB: hw4_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  postgres_data:
