version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/shop
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local