global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: demo-service-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - local:8080

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
