version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shop_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  local:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/shop_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: