version: "3"

services:

  local:
    build:
      context: ..
      dockerfile: ./shop_api/Dockerfile
      target: local
    restart: always
    ports:
      - 8080:8080
    environment:
      - APP_ROOT=/app
    networks:
      - shop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      - shop-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  prometheus-data:
