# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shop_pb2 as shop__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShopStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCart = channel.unary_unary(
                '/shop.Shop/CreateCart',
                request_serializer=shop__pb2.Empty.SerializeToString,
                response_deserializer=shop__pb2.Id.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/shop.Shop/GetCart',
                request_serializer=shop__pb2.Id.SerializeToString,
                response_deserializer=shop__pb2.Cart.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/shop.Shop/AddToCart',
                request_serializer=shop__pb2.AddToCartRequest.SerializeToString,
                response_deserializer=shop__pb2.Cart.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/shop.Shop/CreateItem',
                request_serializer=shop__pb2.ItemCreate.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/shop.Shop/GetItem',
                request_serializer=shop__pb2.Id.SerializeToString,
                response_deserializer=shop__pb2.Item.FromString,
                _registered_method=True)


class ShopServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCart,
                    request_deserializer=shop__pb2.Empty.FromString,
                    response_serializer=shop__pb2.Id.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=shop__pb2.Id.FromString,
                    response_serializer=shop__pb2.Cart.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=shop__pb2.AddToCartRequest.FromString,
                    response_serializer=shop__pb2.Cart.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=shop__pb2.ItemCreate.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=shop__pb2.Id.FromString,
                    response_serializer=shop__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shop.Shop', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shop.Shop', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Shop(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/CreateCart',
            shop__pb2.Empty.SerializeToString,
            shop__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetCart',
            shop__pb2.Id.SerializeToString,
            shop__pb2.Cart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/AddToCart',
            shop__pb2.AddToCartRequest.SerializeToString,
            shop__pb2.Cart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/CreateItem',
            shop__pb2.ItemCreate.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shop.Shop/GetItem',
            shop__pb2.Id.SerializeToString,
            shop__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
