# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shop.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshop.proto\x12\x04shop\"\x07\n\x05\x45mpty\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\nItemCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"@\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\"(\n\x08\x43\x61rtItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"@\n\x04\x43\x61rt\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.shop.CartItem\x12\r\n\x05price\x18\x03 \x01(\x01\"4\n\x10\x41\x64\x64ToCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x0f\n\x07item_id\x18\x02 \x01(\x05\x32\xca\x01\n\x04Shop\x12#\n\nCreateCart\x12\x0b.shop.Empty\x1a\x08.shop.Id\x12\x1f\n\x07GetCart\x12\x08.shop.Id\x1a\n.shop.Cart\x12/\n\tAddToCart\x12\x16.shop.AddToCartRequest\x1a\n.shop.Cart\x12*\n\nCreateItem\x12\x10.shop.ItemCreate\x1a\n.shop.Item\x12\x1f\n\x07GetItem\x12\x08.shop.Id\x1a\n.shop.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_ID']._serialized_start=29
  _globals['_ID']._serialized_end=45
  _globals['_ITEMCREATE']._serialized_start=47
  _globals['_ITEMCREATE']._serialized_end=88
  _globals['_ITEM']._serialized_start=90
  _globals['_ITEM']._serialized_end=154
  _globals['_CARTITEM']._serialized_start=156
  _globals['_CARTITEM']._serialized_end=196
  _globals['_CART']._serialized_start=198
  _globals['_CART']._serialized_end=262
  _globals['_ADDTOCARTREQUEST']._serialized_start=264
  _globals['_ADDTOCARTREQUEST']._serialized_end=316
  _globals['_SHOP']._serialized_start=319
  _globals['_SHOP']._serialized_end=521
# @@protoc_insertion_point(module_scope)
