version: "3.8"

services:
  local:
    build:
      context: ./shop_api
      dockerfile: Dockerfile
      target: local
    container_name: shop_api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    volumes:
      - ./shop_api/src:/app
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./settings/grafana:/var/lib/grafana
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    restart: always
    networks:
      - monitoring_network

volumes:
  prometheus_data:

networks:
  monitoring_network:
    driver: bridge
