services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge
