{
 "title": "HW3 Application Metrics",
 "description": "HW3 Application Metrics",
 "tags": [
  "webapp",
  "python",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds) / 3600",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (method, status)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}