version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: hw_api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/shop_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  tests:
    build: .
    container_name: hw_tests
    environment:
      - TESTING=1
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/test_shop_db
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      bash -c "
        echo '🧪 Lancement des tests unitaires...';
        pytest -v --maxfail=1 --disable-warnings
      "

volumes:
  postgres_data:
