global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: shop-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - shop_api:8000
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
