version: "3.9"

services:
  db:
    image: postgres:16
    container_name: shop-pg
    environment:
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
      - POSTGRES_DB=shop
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 3s
      retries: 50
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg://shop:shop@db:5432/shop
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

volumes:
  pg-data:
