global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "shop-api"
    static_configs:
      - targets: ["shop-api:8000"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
