{
 "title": "Business Metrics",
 "panels": [
  {
   "title": "Carts Created per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(shop_carts_created_total[1m])",
     "legendFormat": "Carts per minute"
    }
   ]
  },
  {
   "title": "Active Chat Rooms",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(shop_ws_connections)" }
   ]
  },
  {
   "title": "Chat Messages per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(shop_ws_messages_total[1m])) by (chat_name)",
     "legendFormat": "{{chat_name}}"
    }
   ]
  },
  {
   "title": "Total Items in Stock",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(shop_items_total)" }
   ]
  }
 ]
}