services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always

  local:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    restart: always
    environment:
      - DATABASE_URL=postgresql://shop:shop@postgres:5432/shopdb
    ports:
      - 8080:8080
    depends_on:
      - prometheus
      - grafana
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      POSTGRES_DB: shopdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres_data: