version: "3"

services:

  local:
    build:
      context: .
      dockerfile: ./DockerfilePytest
      target: local
    restart: no
    ports:
      - 8080:8080
    environment:
      PYTHONPATH: .
      SHOP_API_DB_TYPE: postgres
      POSTGRES_ADDRESS: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always

volumes:
  grafana-storage: {}
