{
 "title": "My Dashboard",
 "description": "Key metrics for the shop API",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "P95 времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов по методам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}