{
 "title": "Shop API Monitoring",
 "tags": [
  "fastapi",
  "shop-api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS - Total, Success & Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Total RPS"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"2..\"}[1m]))",
     "legendFormat": "Success RPS"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m]))",
     "legendFormat": "Error RPS"
    }
   ]
  },
  {
   "title": "Latency - Response Time & Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Average Response Time"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Total Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Success & Error Rates (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"2..\"}[1m])) / sum(rate(http_requests_total[1m]))) * 100",
     "legendFormat": "Success Rate %"
    },
    {
     "expr": "(sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) / sum(rate(http_requests_total[1m]))) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  }
 ]
}