name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      working-directory: hw2/hw
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with coverage
      working-directory: hw2/hw
      run: |
        pytest -v --cov=shop_api --cov-report=term-missing --cov-report=xml
    
    - name: Check coverage threshold
      working-directory: hw2/hw
      run: |
        coverage report --fail-under=95