global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: shop-service-prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - local:8080
