version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  local:
    build:
      context: ./shop_api
      dockerfile: Dockerfile
      target: local
    container_name: shop_api
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./shop_api/src:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://shop_user:shop_password@db:5432/shop_db

volumes:
  postgres_data:
