version: "3"

services:

  postgres:
    image: postgres:15
    container_name: hw5_postgres
    environment:
      POSTGRES_DB: hw5_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  local:
    container_name: hw5_local
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
      target: local
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: