name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hw2/hw/requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest -q hw2/hw --cov=hw2/hw --cov-report=term --cov-fail-under=95
