name: "HW5 Tests"

# Запускаем тесты при изменении файлов в hw2/hw/
on:
  pull_request:
    branches: [ main ]
    paths: [ 'hw5/shop_api/**' ]
  push:
    branches: [ main ]
    paths: [ 'hw5/shop_api/**' ]

jobs:
  test-hw5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: hw5/shop_api/
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: hw5/shop_api/
      env:
        PYTHONPATH: ${{ github.workspace }}/hw5/shop_api/
      run: |
        pytest test_shop_api.py -v
