name: "HW2 Tests Custom (with Postgres)"

# Запускаем тесты при изменении файлов в hw2/hw/
on:
  pull_request:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]
  push:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]

jobs:
  test-hw2-custom:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw2/hw

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shop_api
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with in-memory database
      env:
        PYTHONPATH: ${{ github.workspace }}/hw2/hw
        SHOP_API_DB_TYPE: in-memory
      run: |
        pytest test_homework2.py -v
    
    - name: Run tests with Postgres database
      env:
        PYTHONPATH: ${{ github.workspace }}/hw2/hw
        SHOP_API_DB_TYPE: postgres
        POSTGRES_ADDRESS: localhost
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: shop_api
        POSTGRES_PORT: 5432
      run: |
        pytest test_homework2.py -v
