name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.13]

    defaults:
      run:
        working-directory: hw5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov fastapi uvicorn httpx

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        pytest --cov=shop_api \
               --cov-report=term-missing \
               --cov-report=xml \
               --cov-report=html \
               tests/

    - name: Upload coverage XML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: coverage.xml

    - name: Upload coverage HTML
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: htmlcov/
