name: Vlad's tests

on:
  push:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]
  pull_request:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd hw2/hw
        pip install -r requiremets.txt
        pip install pytest pytest-cov pytest-asyncio requests

    - name: Start all services with docker-compose
      run: |
        cd hw2/hw
        docker-compose up -d
        sleep 30  # Даем время всем сервисам запуститься


    - name: Run homework tests
      run: |
        cd hw2/hw
        pytest test_my_test.py -v

    - name: Stop services
      if: always()
      run: |
        cd hw2/hw
        docker-compose down

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml