name: Vlad's tests

on:
  push:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]
  pull_request:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: shop_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hw2/hw/requiremets.txt
        pip install pytest pytest-cov pytest-asyncio asyncpg redis requests
        pip install uvicorn fastapi prometheus-fastapi-instrumentator

    - name: Wait for services
      run: |
        sleep 5

    - name: Start FastAPI app in background
      run: |
        python -m uvicorn hw2/hw/shop_api.main:app --host 0.0.0.0 --port 8080 &
        echo "FastAPI app starting..."
        sleep 5

    - name: Check app health
      run: |
        curl -f http://localhost:8080/ || exit 1
        echo "✅ FastAPI app is healthy"

    - name: Run homework tests
      run: |
        pytest test_my_test.py -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml