name: "HW5 Tests"

on:
  pull_request:
    branches: [ main ]
    paths: [ 'hw4_5/**' ]
  push:
    branches: [ main ]
    paths: [ 'hw4_5/**' ]

jobs:
  tests-hw5:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: hw4_5/requirements.txt

      - name: Install deps
        run: pip install -r hw4_5/requirements.txt

      - name: Run tests (hw5)
        working-directory: hw4_5
        env:
          PYTHONPATH: ${{ github.workspace }}/hw4_5
        run: pytest -q --cov=src --cov-report=term-missing

      - name: DB alembic migrations
        working-directory: hw4_5
        env:
          PYTHONPATH: ${{ github.workspace }}/hw4_5
        run: PYTHONPATH=. alembic upgrade head