name: Vlad's tests

on:
  push:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]
  pull_request:
    branches: [ main, develop, hw2 ]
    paths: [ 'hw2/hw/**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd hw2/hw
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio requests uvicorn

    - name: Start FastAPI app in background
      run: |
        cd hw2/hw
        python -c "from shop_api.main import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=8080)" &
        echo "FastAPI app starting..."
        sleep 3

    - name: Check app health
      run: |
        curl -f http://localhost:8080/ || exit 1
        echo "✅ FastAPI app is healthy"

    - name: Run homework tests
      run: |
        cd hw2/hw
        pytest test_my_test.py -v --cov=. --cov-report=term-missing

    - name: Stop services
      if: always()
      run: |
        # Останавливаем все процессы на порту 8080
        pkill -f "uvicorn" || true