
name: HW5 Tests

on:
  push:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]

jobs:
  test-hw5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: shop_db
          POSTGRES_USER: shop_user
          POSTGRES_PASSWORD: shop_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: hw2/hw
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      working-directory: hw2/hw
      env:
        DATABASE_URL: postgresql://shop_user:shop_password@localhost:5432/shop_db
        PYTHONPATH: ${{ github.workspace }}/hw2/hw
      run: |
        pytest tests/test_shop_api.py --cov=shop_api --cov-report=term -v
