name: Shop API Tests

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'hw2/hw/shop_api/**'
      - '.github/workflows/shop_api_tests.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'hw2/hw/shop_api/**'
      - '.github/workflows/shop_api_tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: shop_db_test
          POSTGRES_USER: shop_user
          POSTGRES_PASSWORD: shop_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      working-directory: hw2/hw
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U shop_user; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run tests with coverage
      working-directory: hw2/hw/shop_api
      env:
        TEST_DATABASE_URL: postgresql://shop_user:shop_password@localhost:5432/shop_db_test
        DATABASE_URL: postgresql://shop_user:shop_password@localhost:5432/shop_db_test
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=95

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./hw2/hw/shop_api/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Generate coverage badge
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Coverage report generated successfully"

    - name: Archive coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: hw2/hw/shop_api/coverage.xml
        retention-days: 30
